config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "matters#index"
  resources :matters
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '農業・林業' },
    { id: 3, name: '漁業' },
    { id: 4, name: '建設' },
    { id: 5, name: '製造' },
    { id: 6, name: '電気・ガス・熱供給・水道' },
    { id: 7, name: '情報通信' },
    { id: 8, name: '運輸業・郵便' },
    { id: 9, name: '卸売業・小売' },
    { id: 10, name: '金融業・保険' },
    { id: 11, name: '不動産・物品賃貸' },
    { id: 12, name: '学術研究・専門・技術サービス' },
    { id: 13, name: '宿泊・飲食サービス' },
    { id: 14, name: '生活関連サービス・娯楽' },
    { id: 15, name: '教育・学術支援' },
    { id: 16, name: '医療・福祉' },
    { id: 17, name: '複合サービス' },
    { id: 18, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :matters
end

app/models/matter.rb
class Matter < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one_attached :image
  belongs_to :user
  belongs_to :genre
  belongs_to :scheduled

  validates :genre_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :scheduled_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :title, presence: true
  validates :info, presence: true
  validates :detail, presence: true
  validates :price,
            numericality: { only_integer: true, greater_than_or_equal_to: 1000, less_than_or_equal_to: 100_000,
                            message: 'is out of setting range' }
  validates :price, presence: true, numericality: { message: 'is invalid. Input half-width characters' }
  validates :image, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/scheduled.rb
class Scheduled < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '週1日以下' },
    { id: 3, name: '週２日' },
    { id: 4, name: '週３日' },
    { id: 5, name: '週４日' },
    { id: 6, name: '週４日以上' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :matters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :matters
  

  validates :nickname, presence: true
  validates :name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: '全角カタカナを使用してください' }
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には半角英字と数字の両方を含めて設定してください'
  validates :profile, presence: true, length: { minimum: 1, maximum: 1000 }
  validates :occupation, presence: true, format: { with: /\A[ぁ-ゔァ-ヴ\p{Ideographic}ａ-ｚＡ-Ｚ０-９]+\z/, message: '全角文字を使用してください' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :name_kana, :profile, :position, :occupation])
  end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_matter, only: [:show, :edit, :update, :destroy]

  def index
    @matters = Matter.all.order(created_at: 'DESC')
  end

  def new
    @matter = Matter.new
  end

  def create
    @matter = Matter.new(matter_params)
    if @matter.valid?
      @matter.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    @matter.update(matter_params)
    if @matter.update(matter_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @matter.user_id == current_user.id && @matter.destroy
  end

  private

  def matter_params
    params.require(:matter).permit(:title, :info, :genre_id, :scheduled_id, :detail, :price,
                                   :image).merge(user_id: current_user.id)
  end

  def set_matter
    @matter = Matter.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index

  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.save
    redirect_to rooms_path(@room)
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end
    
     
    
    private
    def room_params
    params.permit(user_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobEnC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matters/edit.html.erb
<div class="matter-contents">
  <header class="matter-header">
    <%= image_tag"job-en-c02.png" , size: '160x120' %>
  </header>

  <div class="matter-main">
    <h2 class="matter">案件情報を入力</h2>
    <%= form_with model: @matter, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="text-bold">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"matter-image" %>
      </div>
    </div>

    <div class="new-matters">
        <div class="text-bold">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class: "matters-text", id:"matter-title", placeholder:"案件名(40文字まで)", maxlength:"40"%>
        <div class="matters-info">
          <div class="text-bold">
            案件内容
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :info, class:"matters-text", id:"matter-info", placeholder:"案件内容(内容を詳細に記入の方お願いします)(1000文字まで)", rows:"15" ,maxlength:"1000" %>
        </div>
    </div>



    <div class="matter-detail">
      <div class="text-bold">案件詳細</div>
      <div class="form">
        <div class="text-bold">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"matter-genre"}) %>
        <div class="text-bold">
          稼働日数・時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:scheduled_id, Scheduled.all, :id, :name, {}, {class:"select-box", id:"matter-scheduled"})%>
        <div class="text-bold">
          特徴・場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"matters-text", id:"matter-detail", placeholder:"(700文字まで)", rows:"15" ,maxlength:"700" %>
        <div class="text-bold">
          時給
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :price, class:"price-input" , id:"matter-price", placeholder:"(半角数字のみ)" %>
        <span class="sell-hour">/h</span>
      </div>
    </div>

    <div class="matter-btn-contents">
      <%= f.submit "変更する" ,class:"matter-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>
  </div>
</div>

app/views/matters/index.html.erb
<%= render "shared/header" %>
<div class="main">

  <div class="title-contents">
    <h2 class="service-title">
      仕事の出会いをきっかけに
    </h2>
    <p class="service-subtitle">
      JOB EN Cとは
    </p>
    <p class="service-explain">
      JOB EN C では、より多くのビジネスマンの方々にお仕事に関わる出会いを提供する
    </p>
    <p class="service-explain">
      ビジネスマッチングアプリです。
    </p>
    <%= link_to new_matter_path, class: 'matter-text' do%>
    <span>案件投稿</span>
    <% end %>
  </div>
  

  <div class="matter-contents">
    <h2 class="title">案件一覧</h2>
  </div>
    <ul class="matter-lists">
    <% @matters.present? %>
    <% @matters.each do |matter| %>
      <li class="list">
        <%= link_to matter_path(matter.id) do%>
        <div class="matter-img-content">
          <%= image_tag matter.image, class: "matter-img" if matter.image.attached? %>
        </div>
        <div class="matter-info">
          <h3 class="matter-title">
            <%= matter.title %>
          </h3>
          <div class="matter-info">
            <%= matter.info %>
          </div>
          <div class="matter-price">
            <span><%= matter.price %>円/h~</span>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>


      <% if @matters.length == 0%>
      <li class="list">
        <%= link_to "#" do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "matter-img"%>
        <% end %>
        <div class="matter-info">
          <h3 class="matter-title">
          投稿してね!
          </h3>
          <div class="info">
          プログラミングができる人募集
          </div>
          <div class="matter-price">
            <span>9999円/h~</span>
          </div>
        </div>
      </li>
      <% end %>
   
    </ul>
  </div>
<%= render "shared/footer"%>

app/views/matters/new.html.erb
<div class="matter-contents">
  <header class="matter-header">
    <%= image_tag"job-en-c02.png" , size: '160x120' %>
  </header>

  <div class="matter-main">
    <h2 class="matter">案件情報を入力</h2>
    <%= form_with model: @matter, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="text-bold">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"matter-image" %>
      </div>
    </div>

    <div class="new-matters">
        <div class="text-bold">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class: "matters-text", id:"matter-title", placeholder:"案件名(40文字まで)", maxlength:"40"%>
        <div class="matters-info">
          <div class="text-bold">
            案件内容
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :info, class:"matters-text", id:"matter-info", placeholder:"案件内容(内容を詳細に記入の方お願いします)(1000文字まで)", rows:"15" ,maxlength:"1000" %>
        </div>
    </div>



    <div class="matter-detail">
      <div class="text-bold">案件詳細</div>
      <div class="form">
        <div class="text-bold">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"matter-genre"}) %>
        <div class="text-bold">
          稼働日数・時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:scheduled_id, Scheduled.all, :id, :name, {}, {class:"select-box", id:"matter-scheduled"})%>
        <div class="text-bold">
          特徴・場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"matters-text", id:"matter-detail", placeholder:"(700文字まで)", rows:"15" ,maxlength:"700" %>
        <div class="text-bold">
          時給
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :price, class:"price-input" , id:"matter-price", placeholder:"(半角数字のみ)" %>
        <span class="sell-hour">/h</span>
      </div>
    </div>

    <div class="matter-btn-contents">
      <%= f.submit "案件投稿" ,class:"matter-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>
  </div>
</div>

app/views/matters/show.html.erb
<%= render "shared/header"%>

<div class="matter-show">
  <div class="matter-box">
    <h2 class="detail-title">案件情報</h2>
    
    <div class="matter-img-content">
      <%= image_tag @matter.image, class:"matter-box-img" if @matter.image.attached? %>
    </div>

    <div class="matter-title-box">
      <span class="title">
        <%= @matter.title%>
      </span>
    </div>

    <div class="info-detail">
      <%= @matter.info %>
    </div>
    
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-matter">投稿者</th>
          <td class="detail-value"><%= @matter.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-matter">時給</th>
          <td class="detail-value"><%= @matter.price %>/h</td>
        </tr>
        <tr>
          <th class="detail-matter">ジャンル</th>
          <td class="detail-value"><%= @matter.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-matter">稼働日数・時間</th>
          <td class="detail-value"><%= @matter.scheduled.name %></td>
        </tr>
        <div class="show-text-bold">
          詳細
        </div>
        <div class="info-detail">
          <%= @matter.detail %>
        </div>
      </tbody>
    </table>
    <% if user_signed_in? %>
      <% if current_user.id == @matter.user_id %>
        <%= link_to "案件の編集", edit_matter_path, method: :get, class: "matter-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", matter_path(@matter.id), method: :delete, class:"matter-destroy" %>
      <% elsif %>
        <%= link_to "案件が気になる",rooms_path(user_ids: [current_user.id, @matter.user.id]), method: :post, class:"matters-btn" %>
      <% end %>
    <% end %>

    <% if user_signed_in? %>
      <% if current_user.id == @matter.user_id %>
        <%= link_to "案件が気になる人を確認する", "#", method: :post, class:"matters-btn"%>
      <% end %>
    <% end %>

  </div>
</div>

app/views/rooms/index.html.erb
<div class="rooms">
  <div class="room-side">
    <div class="side-header">
      <%= image_tag"job-en-c02.png", class:"rooms-icon" %>
    </div>


  <% current_user.rooms.each do |room| %>
  <div class="side-main">
    <div class="room">
      <div class="room-name">
      <% @another_user = (room.users.where.not(id: current_user.id).to_a)[0] %>
        <%= link_to @another_user.nickname, "#" %>
      </div>
    </div>

    <div class="delete-room">
      <%= link_to "×", room_path(room), method: :delete %>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message|%>
    <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-contents">
  <%= image_tag"job-ec-c03.png", class:"footer-logo" %>
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="top-page-header">
    <div class="area_logo_header">
      <%= image_tag"job-en-c02.png", class:"job-en-c-icon" %>
    </div>

    <div class="nav">
      <ul class="lists-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
          <li><%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% else %>
          <li><%= link_to 'ログイン',new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録',new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class="second-footer">
</footer>

app/views/shared/_second-header.html.erb
<header class="second-header">
      <%= image_tag"job-en-c04.png", class:"second-icon" %>
</header>